# This workflow will do a clean install of node dependencies, cache/restore them, lint the code, and release a new version (if it's a tagged commit)

name: CI for outline-writer

on:
  push:
    branches: [ main ]
    paths:
      - 'outline-writer/**'
    tags: 'outline-writer/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'outline-writer/**'

defaults:
  run:
    working-directory: outline-writer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
        cache-dependency-path: outline-writer/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run deploy
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
